### ISSUE TITLE
Prettier README

### ISSUE THREAD

**Issue by kosich** [JWO719/rxjs-web#14]
May I suggest moving things around in the README to make things more appealing and API easier to navigate?

Here are some ideas:
- reformat the header: add description & badges
- change the copy for the overview section (add links to some articles?)
- split the warnings into a separate section
- add install section
- prioritize API and examples
- deprioritize roadmap and move to the bottom (I'd actually moved the roadmap into a separate file)

Something like this:

------

<div align="center">

<img src="https://github.com/niklas-wortmann/rxjs-web/raw/development/docs/assets/rxjs-web-logo.svg" alt="RxJS Web Logo" width="86" height="86">

<h1>
rxjs-web

<br/>
<sup><sub>Observables for the Browser API</sub></sup>
<br/>

<a href="https://www.npmjs.com/package/rxjs-web"><img src="https://img.shields.io/npm/v/rxjs-web" alt="NPM"></a> <a href="https://bundlephobia.com/result?p=rxjs-web@latest"><img src="https://img.shields.io/bundlephobia/minzip/rxjs-web?label=gzipped" alt="Bundlephobia"></a> <a href="https://opensource.org/licenses/MIT" rel="nofollow"><img src="https://img.shields.io/npm/l/rxjs-web" alt="MIT license"></a>

<br/>
</h1>

</div>

This library aims to provide an `observable` based API, that wraps the web APIapi. This also includes experimental, non-standard, and not well-supported APIs. Polyfills need to be provided by the user of this library if necessary.

## 📦 Install

```
npm i rxjs-web
```

This library uses the Observable implementation of [rxjs >= 6](https://www.npmjs.com/package/rxjs) and expects you already have that installed in your project.

## ⚠️ A word of warning

The public API surface of this library can be affected by breaking changes within the experimental API used.

Additionally, the implementation of this library makes use of [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) which breaks ie <= 11! There is no plan to add support for IE 11 in this library.

## 🔧 API Reference

General Hint: Usually Promises are eager. All the APIs provided by this library, that wraps native promise-based APIs, are lazy though. This design decision was made due to the general specification of Observables.

### fromIntersectionObserver

_⚠️ experimental_ _✅ tested_

[MDN link](https://developer.mozilla.org/)

description

```ts
const example = fromIntersectionObserver();
// ...
```

### fromMutationObserver

_⚠️ experimental_ _🔬 not well tested_

[MDN link](https://developer.mozilla.org/)

description

```ts
const example = fromMutationObserver();
// ...
```

## Supported API Roadmap

| API                                                                                                               | Implemented | Tested  | Experimental/not well supported |
| ----------------------------------------------------------------------------------------------------------------- | ----------- | ------- | ------------------------------- |
| [Bluetooth API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API)                               |             |         | &#9745;                         |
| [Broadcast Channel API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API)                   |             |         |                                 |
| [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)             | &#9745;     |         |                                 |
| [File and Directory Entries API](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API) |             |         | &#9745;                         |
| [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation)                         | &#9745;     |         |                                 |
| [Image Capture API](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Image_Capture_API)               |             |         | &#9745;                         |
| [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)                | &#9745;     |         | &#9745;                         |
| [matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia)                                  | &#9745;     |         |                                 |
| [MutationObserver](https://developer.mozilla.org/de/docs/Web/API/MutationObserver)                                | &#9745;     |         |                                 |
| [Network Information API](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation)                    | &#9745;     |         | &#9745;                         |
| [PerformanceObserver](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver)                       | &#9745;     |         | &#9745;                         |
| [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API)                                             |             |         | &#9745;                         |
| [Permission API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions)                                    | &#9745;     |         | &#9745;                         |
| [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)                                 | &#9745;     |         | &#9745;                         |
| [Sensor APIs](https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs)                                       | &#9745;     |         | &#9745;                         |
| [Vibration API](https://developer.mozilla.org/en-US/docs/Web/API/Vibration_API)                                   |             |         | &#9745;                         |

## Credits

This project is build upon the [typescript library starter](https://github.com/alexjoverm/typescript-library-starter). Kudos to [@alexjoverm](https://twitter.com/alexjoverm) and every contributor of this amazing project!

Many thanks also goes to [Sascha Nuissl](https://twitter.com/saschanuissl) for creating this fantastic logo!

**Comment by niklas-wortmann** [comment]
Wow that looks amazing. Please submit a PR with those changes. I would highly appreciate it
